### ISSUE TITLE
Path Traversal

### ISSUE THREAD

**Issue by findyoky** [CSGY-9223-Group4/lab1#8]
**Reference**: [SNYK issue link](https://app.snyk.io/org/findyoky/project/ffbb9829-9e84-439e-b13b-8f0f1e8467d7#issue-a662074d-ded2-4958-b7d4-6526364c52ce)

**File**: ‎src/config.py
Code line: 13 & 16
![Screenshot 2024-09-23 194239](https://github.com/user-attachments/assets/526e1242-53eb-4714-832b-8031818fd250)

**Issue:** Unsanitized input from an environment variable flows into open, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to read arbitrary files.

Details
A Directory Traversal attack (also known as path traversal) aims to access files and directories that are stored outside the intended folder. By manipulating files with "dot-dot-slash (../)" sequences and its variations, or by using absolute file paths, it may be possible to access arbitrary files and directories stored on file system, including application source code, configuration, and other critical system files.

Being able to access and manipulate an arbitrary path leads to vulnerabilities when a program is being run with privileges that the user providing the path should not have. A website with a path traversal vulnerability would allow users access to sensitive files on the server hosting it. CLI programs may also be vulnerable to path traversal if they are being ran with elevated privileges (such as with the setuid or setgid flags in Unix systems).

Directory Traversal vulnerabilities can be generally divided into two types:

Information Disclosure: Allows the attacker to gain information about the folder structure or read the contents of sensitive files on the system.
st is a module for serving static files on web pages, and contains a [vulnerability of this type](https://snyk.io/vuln/npm:st:20140206). In our example, we will serve files from the public route.

If an attacker requests the following URL from our server, it will in turn leak the sensitive private key of the root user.

curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.ssh/id_rsa
Note %2e is the URL encoded version of . (dot).

Writing arbitrary files: Allows the attacker to create or replace existing files. This type of vulnerability is also known as Zip-Slip.
One way to achieve this is by using a malicious zip archive that holds path traversal filenames. When each filename in the zip archive gets concatenated to the target extraction folder, without validation, the final path ends up outside of the target folder. If an executable or a configuration file is overwritten with a file containing malicious code, the problem can turn into an arbitrary code execution issue quite easily.

The following is an example of a zip archive with one benign file and one malicious file. Extracting the malicious file will result in traversing out of the target folder, ending up in /root/.ssh/ overwriting the authorized_keys file:

2018-04-15 22:04:29 .....           19           19  good.txt
2018-04-15 22:04:42 .....           20           20  ../../../../../../root/.ssh/authorized_keys
![Screenshot 2024-09-23 194239](https://github.com/user-attachments/assets/5a1bdf15-ee15-4c24-bcf3-4d418b44a901)

**Comment by elveskevtar** [comment]
Fixed by https://github.com/CSGY-9223-Group4/lab1/pull/19
@wbc2025 please review!

**Comment by wbc2025** [comment]
reviewed!
